[package]
name = "kubectl-spy"
version = "0.1.0"
authors = ["Eric Lemieux <eric@lemieuxdev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
base64 = "0.13.0"
kube = {version= "~0.74.0", features=["derive", "runtime"]}
kube-derive = "~0.83.0"
kube-runtime = "~0.74.0"
k8s-openapi = {version = "~0.15.0", features = ["v1_18"] }

tokio = { version = "1", features = ["full"] }

serde = "1.0.164"
serde_json = "1.0.96"
