[package]
name = "kubectl-spy"
version = "0.1.0"
authors = ["Eric Lemieux <eric@lemieuxdev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
base64 = "0.13.0"
kube = "0.56.0"
kube-runtime = "0.56.0"
k8s-openapi = {version = "0.11.0", features = ["v1_16"] }

tokio = { version = "1", features = ["full"] }

serde = "1.0.133"
serde_json = "1.0.81"
