name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: |
          cargo clippy --fix -- \
            -W clippy::pedantic \
            -W clippy::nursery \
            -W clippy::unwrap_used \
            -W clippy::expect_used
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: make build
      - uses: helm/kind-action@v1.8.0
        with:
          wait: 120s
      - run: make test-e2e
